### ISSUE TITLE
Looks like not support extraquerylistfile in 1.2.4 version

### ISSUE THREAD

**Issue by yuanyuefeng** [wanghy8166/orabbix#1]
Hi wanghy8166,

I download shared jar file(1.2.4) and replace 1.2.3 jar file. Looks like not support "dbxxx.ExtraQueryListFile" there ,only return value of items which located in "dbxxx.QueryListFile". 

Is there anything change above in 1.2.4 jar files?

**Comment by yuanyuefeng** [comment]
Or, could u kindly share the source of 1.2.4 java files ? Appreciate for your help.

**Comment by wanghy8166** [comment]
I have not tested on ExtraQueryListFile.

**Comment by wanghy8166** [comment]
> Hi wanghy8166,
> 
> I download shared jar file(1.2.4) and replace 1.2.3 jar file. Looks like not support "dbxxx.ExtraQueryListFile" there ,only return value of items which located in "dbxxx.QueryListFile".
> 
> Is there anything change above in 1.2.4 jar files?

Please try the orabbix-1.2.4w.jar file

**Comment by ultramanyuan** [comment]
Hi wanghy8166,
i downloaded orabbix-1.2.4w.jar file and start to run, following error prompt:
**"Error: Could not find or load main class com.smartmarmot.orabbix.bootstrap"**

**Comment by yuanyuefeng** [comment]
Hi wanghy8166,

It works fine!  Appreciate for your great help.
