### ISSUE TITLE
run time error

### ISSUE THREAD

**Issue by allexmasu** [wanghy8166/orabbix#2]
when I try to run the service，it says "Error: Could not find or load main class com.smartmarmot.orabbix.bootstrap" ? Any suggestion?

**Comment by wanghy8166** [comment]
> when I try to run the service，it says "Error: Could not find or load main class com.smartmarmot.orabbix.bootstrap" ? Any suggestion?

What is your zabbix version?
What is the corresponding jdk version when orabbix starts?
And show the full orabbix.log

**Comment by allexmasu** [comment]
4.0.3

**Comment by allexmasu** [comment]
> > when I try to run the service，it says "Error: Could not find or load main class com.smartmarmot.orabbix.bootstrap" ? Any suggestion?
> 
> What is your zabbix version?
> What is the corresponding jdk version when orabbix starts?

openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-b12)
zabbix 4.0.3

**Comment by allexmasu** [comment]
The service can't be started ,and  log file  is empty. If i use old version jar file，everythng is ok.  
FYI
-------------------------------------------------------------------------------------
[root@zabbix orabbix]# ./run.sh 
[root@zabbix orabbix]# Error: Could not find or load main class com.smartmarmot.orabbix.bootstrap

[root@zabbix orabbix]# service orabbix start
Starting orabbix (via systemctl):                          [  OK  ]
[root@zabbix orabbix]# service orabbix status
Orabbix is stopped
[root@zabbix orabbix]# ps -ef|grep orabbix
root     63308 57622  0 13:18 pts/1    00:00:00 grep --color=auto orabbix
[root@zabbix orabbix]# ls logs/
orabbix.log.1  orabbix.pid
[root@zabbix orabbix]# jave -version
bash: jave: command not found...
[root@zabbix orabbix]# java -version
openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)

**Comment by wanghy8166** [comment]
In my environment, working fine:
[root@o183rpm ~]# cat /etc/redhat-release 
CentOS Linux release 7.5.1804 (Core) 
[root@o183rpm ~]# java -version
openjdk version "1.8.0_161"
OpenJDK Runtime Environment (build 1.8.0_161-b14)
OpenJDK 64-Bit Server VM (build 25.161-b14, mixed mode)

You can try rebooting the operating system and then checking the orabbix.logs
Or change to a new environment, try again
