### ISSUE TITLE
Error on Querybox java.lang.NullPointerException

### ISSUE THREAD

**Issue by FishInThePool** [wanghy8166/orabbix#3]
in CentOS7.4  jdk1.8

log error:
........ 
Error on Querybox java.lang.NullPointerException
........
Error Orabbix Errot on dbjob for database  xxx QueryList error java.lang.IllegalArugementException : 'query'
array is empty or null

emm i try jdk 1.7 or openjdk 1.8.0_131 does,t use

**Comment by wanghy8166** [comment]
用 orabbix-1.2.4w.jar
在 config.props 增加配置 orcl2.ExtraQueryListFile=./conf/query_extra.props 
确保 query_extra.props 存在且有效

**Comment by lvtu0316** [comment]
> 用 orabbix-1.2.4w.jar
> 在 config.props 增加配置 orcl2.ExtraQueryListFile=./conf/query_extra.props
> 确保 query_extra.props 存在且有效

orabbix-1.2.4w.jar 是替换根目录的 orabbix-1.2.3.jar 还是放在同级目录呢？

**Comment by FishInThePool** [comment]
> > 用 orabbix-1.2.4w.jar
> > 在 config.props 增加配置 orcl2.ExtraQueryListFile=./conf/query_extra.props
> > 确保 query_extra.props 存在且有效
> 
> orabbix-1.2.4w.jar 是替换根目录的 orabbix-1.2.3.jar 还是放在同级目录呢？
这个其实是无所谓的，可以改启动脚本，如果你不改可以直接把orabbix-1.2.4w.jar名字改成orabbix-1.2.3.jar替换掉就好了

**Comment by lvtu0316** [comment]
> > > 用 orabbix-1.2.4w.jar
> > > 在 config.props 增加配置 orcl2.ExtraQueryListFile=./conf/query_extra.props
> > > 确保 query_extra.props 存在且有效
> > 
> > 
> > orabbix-1.2.4w.jar 是替换根目录的 orabbix-1.2.3.jar 还是放在同级目录呢？
> > 这个其实是无所谓的，可以改启动脚本，如果你不改可以直接把orabbix-1.2.4w.jar名字改成orabbix-1.2.3.jar替换掉就好了

我把他放在同级目录下，也可以，谢谢！

**Comment by powersam** [comment]
程序是跑正常了,但是zabbix 上显示不了数据了... version : 4.0.4.
